paths:
  /products:
    get:
      summary: Obtener todos los productos
      description: Obtiene una lista de todos los productos disponibles.
      responses:
        "200":
          description: Lista de productos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/definitions/Product'
    post:
      summary: Crear un nuevo producto
      description: Crea un nuevo producto. (Requiere rol "admin" o "premium")
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/definitions/Product'
      responses:
        "200":
          description: Producto creado
          content:
            application/json:
              schema:
                $ref: '#/definitions/Product'
  /products/{id}:
    get:
      summary: Obtener un producto por ID
      description: Obtiene un producto por su ID.
      responses:
        "200":
          description: Producto encontrado
          content:
            application/json:
              schema:
                $ref: '#/definitions/Product'
        "404":
          description: Producto no encontrado
    put:
      summary: Actualizar un producto
      description: Actualiza un producto existente. (Requiere rol "admin" o "premium")
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/definitions
